Script started on 2016年03月08日 (週二) 19時53分49秒
]0;F74046404@2015cpp: ~/lab1F74046404@2015cpp:~/lab1$ git clone https://github.com/lgc0502/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[2Pwhoami; pwd./A[Kg++ -o A A.cpp
]0;F74046404@2015cpp: ~/lab1F74046404@2015cpp:~/lab1$ g++ -o A A.cppit clone https://github.com/lgc0502/lab1.git[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[Config -l[K[2Pwhoami; pwd./A[K
please enter a number:22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;F74046404@2015cpp: ~/lab1F74046404@2015cpp:~/lab1$ exit

Script done on 2016年03月08日 (週二) 19時54分05秒
